name: Go

on:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

  unittest:
    name: Go test
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./source
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Generate coverage report
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
 
    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        token: 573af21b-2de0-49e0-beff-5a7b3489b99f
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        





