name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  unittest:
    name: Go test
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./source

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Generate coverage report
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
